[FIX] themeSwitch class + [ADD] password component + ...
alireza0/x-ui pull request #311
Opened 2023-05-15 18:34 UTC by hamid-gh98

- fix darkClass in themeSwitcher
- update sub remarks
- add password component
- update docker-compose
- fix and update some translations

2023-05-15 19:41 UTC, alireza0 requested changes
Good job!
Please fix this minor changes due happened to parallel commits.

2023-05-15 19:41 UTC, alireza0 commented on web/assets/js/util/common.js
> -  }
It is about a conflict. Please fix it

2023-05-15 19:41 UTC, alireza0 commented on web/html/xui/form/tls_settings.html
This one is updated in parallel. Please rebase it.

2023-05-15 20:56 UTC, hamid-gh98 commented
Hello @alireza0,
Done.

2023-05-15 22:03 UTC, hamid-gh98 commented
btw, when I go to settings.html, it says that `areAllItemsExist` is not defined.
so, I moved its function to `settings.html` and renamed it to `doAllItemsExist`.

![image](https://github.com/alireza0/x-ui/assets/70919649/31d46c45-7c22-471a-b202-003d66a6035f)

2023-05-16 01:45 UTC, hamid-gh98 commented
I also now split the country configs (block + direct) in settings page.
hope that helps better

2023-05-16 07:59 UTC, alireza0 commented
> btw, when I go to settings.html, it says that `areAllItemsExist` is not defined. so, I moved its function to `settings.html` and renamed it to `doAllItemsExist`.
> 
> ![image](https://user-images.githubusercontent.com/70919649/238482339-31d46c45-7c22-471a-b202-003d66a6035f.png)

Actually it was defined [here](https://github.com/alireza0/x-ui/blob/main/web/assets/js/util/common.js#L109:L116) , but it seems in your branch it was not updated.
It is better to have general functions in `common.js` instead of directly push it to busy file like settings.
Please move `areAllItemsExist` or `doAllItemsExist` to its right place.
Overall your job is great! Thanks a lot

2023-05-16 09:48 UTC, hamid-gh98 commented
> > btw, when I go to settings.html, it says that `areAllItemsExist` is not defined. so, I moved its function to `settings.html` and renamed it to `doAllItemsExist`.
> 
> Actually it was defined [here](https://github.com/alireza0/x-ui/blob/main/web/assets/js/util/common.js#L109:L116) , but it seems in your branch it was not updated. It is better to have general functions in `common.js` instead of directly push it to busy file like settings. Please move `areAllItemsExist` or `doAllItemsExist` to its right place. Overall your job is great! Thanks a lot

ok, i removed it from `settings.html`.
thanks.

2023-05-16 09:50 UTC, merged

2023-05-16 09:51 UTC, alireza0 commented
Well done!