Translation - RU
alireza0/x-ui pull request #473
Opened 2023-08-08 21:31 UTC by Saph1s

Edited RU translation

2023-08-08 22:22 UTC, MHSanaei requested changes

2023-08-08 22:22 UTC, MHSanaei commented on web/translation/translate.ru_RU.toml
> +"success" = Успешно"
```suggestion
"success" = "Успешно"
```

2023-08-09 18:47 UTC, vlbaybekov commented
As russian i can approve, this is legit

2023-08-09 19:04 UTC, merged

2023-08-09 19:08 UTC, alireza0 commented
Thanks :)