Added advanced Geo update menu  x-ui.sh
alireza0/x-ui pull request #690
Opened 2023-12-04 05:30 UTC by Shellgate

A request menu is created with a submenu

2023-12-04 06:14 UTC, Shellgate commented
![IMG_۲۰۲۳۱۲۰۴_۰۹۳۸۵۰](https://github.com/alireza0/x-ui/assets/128194280/4eb53337-9ef3-49f2-9b37-3a50f7b58ff8)
![IMG_۲۰۲۳۱۲۰۴_۰۹۳۹۲۸](https://github.com/alireza0/x-ui/assets/128194280/7932a842-c4aa-4991-85d3-38b158dbb380)


Everything is ok 👌 but i dont add iran.dat 
Will add it to menu if you want to delete it letter you can edit it letter

2023-12-04 06:44 UTC, Shellgate commented
![IMG_۲۰۲۳۱۲۰۴_۱۰۱۰۳۵](https://github.com/alireza0/x-ui/assets/128194280/382f0c6b-5f23-44cb-aabe-2ab7f0efc7f1)
![IMG_۲۰۲۳۱۲۰۴_۱۰۱۰۵۱](https://github.com/alireza0/x-ui/assets/128194280/5ec941bc-92cb-4207-a0d1-e116eb565f00)


The menu was fully tested and everything is correct 

Also, if you intend to remove it in the future iran.dat You can edit it, the panel was updated with both options and it works without any problems

2023-12-04 17:21 UTC, Enkidu-6 commented
A couple of things:

On lines 633 and 653 you're deleting all the .dat files ( which is not a good idea ) and then you're using wget -N, which means you're asking wget to download the files if they're newer than the local files. Well, there are no local files. You just deleted them.

Also when I choose update the geofiles, I expect them to be updated. I don't expect the files modified or anything added that wasn't in the original program. You're adding two geofiles ( named geoip_IR.dat and geosite_IR.dat ) that don't exist in the original panel and from a source that doesn't exist in the original panel. Not to mention that the Panel and users of it have no rules that uses them. So why are we adding new files to the panel and calling it an update?

If @alireza0 decides that those files are needed, that's his prerogative and he will add them to the original source but until then, in my view, we shouldn't modify them.

Last but not least, I'm not sure why you insist on adding files from jsdelivr but your menu is simply offering people a choice to update from two different sources. This implies that they are simply mirrors of the same repository and does not disclose that they will be downloading two completely different files and any rules they may already have that uses those files, may actually break.

Cheers.

2023-12-04 18:06 UTC, Shellgate commented
There is no problem. In the first answer, I can say that instead of manually importing files, I want to delete all these files or extensions .dat are deleted 

A lot of effort has been made for these items. Do not add sieves inside these

2023-12-04 18:18 UTC, Enkidu-6 commented
> A lot of effort has been made for these items. Do not add sieves inside these

Your efforts are very much appreciated. I'm just saying that those efforts are made in the wrong direction. If I for example choose option 2 in the menu, I expect to get the newest version of Alireza's panel. I don't want to end up with Sanaei's or Marzban Panel. By the same token, option 18 should give me the newest versions of the existing Geofiles, Not a bunch of other files.

Cheers.

2023-12-04 18:25 UTC, Shellgate commented
You should research more about these things. I have been making a new version for two days and will publish it soon

However, the current version that has been updated provides you with the most serious roles First, I clearly mentioned that all Fa.dat They will be deleted, so there is no need to name them all because they are the same b In the second case, the rolls take the latest version, the rolls of Iran are replaced instead of the Iran file in all of these, and they are complementary to the Iran file.

2023-12-04 19:34 UTC, alireza0 requested changes
Thanks a lot. It is a kind of great job.
Please make a decision delete or using -N, and also ask for restart in advance.

2023-12-04 19:34 UTC, alireza0 commented on x-ui.sh
> +    rm -f *.dat
Please don't remove the files when you are using -N swith

2023-12-04 19:34 UTC, alireza0 commented on x-ui.sh
> +    rm -f *.dat
Please don't remove the files when you are using -N swith

2023-12-04 19:34 UTC, alireza0 commented on x-ui.sh
> +    systemctl restart x-ui
It would be nice if you can ask for restart in advance

2023-12-04 19:34 UTC, alireza0 commented on x-ui.sh
> +    systemctl restart x-ui
It would be nice if you can ask for restart in advance.

2023-12-05 00:50 UTC, closed without merging

2023-12-05 00:51 UTC, Shellgate commented
I will upload the new version soon, I really worked very well and it is a perfect example