Add wireguard to xray outbound
alireza0/x-ui pull request #763
Opened 2023-12-14 09:55 UTC by sudospaes

Xray (1.6.5+) has added outbound WireGuard support. 
With this feature, we can use Warp or any WireGuard configuration in outbounds. I added the WireGuard template to x-ui to make it easier to use this feature.

<img width="402" alt="Screenshot 2023-12-14 130400" src="https://github.com/alireza0/x-ui/assets/79229394/8bfce908-51b9-4fec-ae9e-ce642e2f3a06">

<img width="402" alt="Screenshot 2023-12-14 130415" src="https://github.com/alireza0/x-ui/assets/79229394/3a39378e-c4d5-4056-86bf-547e8a9873b6">

Thank you for developing x-ui alireza ❤️

2023-12-14 13:41 UTC, alireza0 requested changes
Thank you for your enhancements.
Actually, I wait for new update's document from xray-core which they support this protocol in inbounds from early version.
It is complete and clean! Good job!

Just please review the comments regarding using i18n and update this PR.
Thanks again

2023-12-14 13:41 UTC, alireza0 commented on web/html/xui/form/outbound.html
> +    <a-form-item label='{{ i18n "pages.xray.outbound.DNS" }}'>
Please don't use i18n translation for well-known abbreviations.
DNS and MTU should be used as same as english words.

2023-12-14 13:41 UTC, alireza0 commented on web/translation/translate.en_US.toml
> +"DNS" = "DNS"
As above

2023-12-14 13:41 UTC, alireza0 commented on web/translation/translate.fa_IR.toml
> +"DNS" = "DNS"
Same

2023-12-14 13:41 UTC, alireza0 commented on web/translation/translate.ru_RU.toml
> +"DNS" = "DNS"
Same

2023-12-14 13:41 UTC, alireza0 commented on web/translation/translate.vi_VN.toml
> +"DNS" = "DNS"
Same

2023-12-14 13:41 UTC, alireza0 commented on web/translation/translate.zh_Hans.toml
> +"DNS" = "域名系统"
Same

2023-12-14 13:45 UTC, alireza0 commented on web/assets/js/model/outbound.js
> +    constructor(MTU, DNS, secretKey, address, publicKey, allowedIPs, endpoint) {
It is also better to pre-define constructor values as much as possible, for example MTU and DNS

2023-12-14 13:46 UTC, alireza0 commented on web/assets/js/model/outbound.js
> +    constructor(MTU, DNS, secretKey, address, publicKey, allowedIPs, endpoint) {
Also use small letters for parameter's name: mtu, dns

2023-12-14 15:05 UTC, sudospaes commented
The requested changes have been applied https://github.com/alireza0/x-ui/pull/763/commits/622772eb6fa36996d358e03de5e1e7f5f23f9b9c

2023-12-14 21:30 UTC, alireza0 requested changes
As I checked, there is no `dns` parameter is `Wireguard` outbound streamSetting.
[please check here](https://xtls.github.io/en/config/outbounds/wireguard.html)

And also please use small letters for `mtu` in toJson() method

2023-12-14 21:30 UTC, alireza0 commented on web/assets/js/model/outbound.js
> +            DNS: this.dns,
mtu should be defined here in small leters

2023-12-15 05:47 UTC, sudospaes commented
> As I checked, there is no `dns` parameter in `Wireguard` outbound streamSetting. [please check here](https://xtls.github.io/en/config/outbounds/wireguard.html)
> 
> And also please use small letters for `mtu` in toJson() method

I have seen it elsewhere. DNS is even available in the Wireguard interface and its clients.

2023-12-15 06:18 UTC, sudospaes commented
I removed "DNS" field because it is not in the xray-core document. Also "keepAlive" field has been added to the template. https://github.com/alireza0/x-ui/pull/763/commits/47949a7c0d50205859feba36a664c2bf68e3a0a1

2023-12-16 22:19 UTC, alireza0 commented
Dear @sudospaes,

Thank you for you effort.

There are some bugs in xray 1.8.6 related to the `wireguard` protocol. I will keep this request be opened till all changes in xray-core be fixed.

2023-12-17 06:44 UTC, sudospaes commented
> Dear @sudospaes,
> 
> Thank you for you effort.
> 
> There are some bugs in xray 1.8.6 related to the `wireguard` protocol. I will keep this request be opened till all changes in xray-core be fixed.

Thank you @alireza0

2023-12-29 13:24 UTC, kalilovers commented
how we can use other wireguard (no warp) ? do we had to make a personal wireguard server for use in our panel or there is other freeone like warp?

2023-12-31 16:05 UTC, alireza0 approved these changes

2024-01-08 16:12 UTC, merged

2024-01-09 22:16 UTC, alireza0 commented
@kalilovers Inbounds and Outbound part are doing different activities.
Outbound in one server will connect to an Inbound from another server.

2024-01-10 06:18 UTC, kalilovers commented
> @kalilovers Inbounds and Outbound part are doing different activities.
> Outbound in one server will connect to an Inbound from another server.

Understood, this is very helpful!

Look, I'm right, if I create a wireguard-type outbound, in this case, I create an inbound, for example, on the American server, then I create the outbound on the my main server, then I can create a rules consisting of several sites and place  Output it to Wireguard Outband, transfer that list from my US server, a bit like Warp, right?